########################
# --- Website Data --- #
########################

baseurl: ""
url: "https://thecodingdodo.com"

#########################################
# --- Default Options for All Pages --- #
#########################################

title: no-title
excerpt: no-description

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "two-col"
      permalink: blog/:slug
      pages: [title, banner, blog]
      sides: [all-posts-same-category]
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "one-col"
      pages: [blog]

######################
# --- Menu Links --- #
######################

menu-links:
  Blog: "/"
  About Me: "/about-me"

######################
# --- Foot Links --- #
######################

foot-links:
  Cookie Policy: "/cookie-policy"
  Privacy Policy: "/privacy-policy"

########################
# --- Social Media --- #
########################

social-media:
  twitter: https://twitter.com/thecodingdodo

###################
# --- Plugins --- #
###################

plugins:
  - jekyll-sitemap