########################
# --- Website Data --- #
########################

baseurl: ""
url: "https://thecodingdodo.com"

#########################################
# --- Default Options for All Pages --- #
#########################################

title: no-title
excerpt: no-description

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "two-column"
      permalink: blog/:slug
      pages: [title, banner, article]
      sides: [all-posts-same-category]
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "one-column"
      pages: [content]

########################
# --- Social Media --- #
########################

social-media:
  twitter: https://twitter.com/thecodingdodo

###################
# --- Plugins --- #
###################

plugins:
  - jekyll-sitemap
  - jekyll-remote-theme

########################
# --- Custom Theme --- #
########################

remote_theme: Dean-J-K-James/dodo-web-engine-jekyll-theme