########################
# --- Website Data --- #
########################

baseurl: ""

#########################################
# --- Default Options for All Pages --- #
#########################################

title: no-title
excerpt: no-description

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: blog/:slug
      page_class: "two-col-s-f flex-16 p-32 px-d-20"
      pages: [title, banner, blog]
      sides: [all-posts-same-category]
  - scope:
      path: ""
    values:
      layout: "default"
      page_class: "one-col p-32 px-d-20"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "one-col"
      pages: [information]

######################
# --- Menu Links --- #
######################

menu-links:
  Blog: "/"
  About Me: "/about-me"

######################
# --- Foot Links --- #
######################

foot-links:
  Cookie Policy: "/cookie-policy"
  Privacy Policy: "/privacy-policy"

########################
# --- Social Media --- #
########################

social-media:
  twitter: https://twitter.com/thecodingdodo

###################
# --- Plugins --- #
###################

plugins:
  - jekyll-sitemap
  - jekyll-analytics

jekyll_analytics:
  GoogleAnalytics: # Add, if you want to track with Google Analytics
    id: G-7K6R0WJX31 # Required - replace with your tracking id
    anonymizeIp: false # Optional - Default: false - set to true for anonymized tracking
