baseurl: "thecodingdodo"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      page_class: "two-col-s-f flex-16 p-32 px-d-20"
  - scope:
      path: ""
    values:
      layout: "default"
      cook_class: "flex-row flex-08 p-08 px-d-20 line-32"
      menu_class: "flex-row flex-08 p-08 px-d-20 line-32"
      page_class: "one-col p-32 px-d-20"
      foot_class: "flex-row flex-08 p-32 px-d-20 line-32"

plugins:
  - jekyll-sitemap

collections:
  posts:
    permalink: /blog/:slug
    