########################
# --- Website Data --- #
########################

baseurl: ""
url: "https://thecodingdodo.com"

#########################################
# --- Default Options for All Pages --- #
#########################################

title: no-title
excerpt: no-description

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "two-column"
      permalink: blog/:slug
      pages: [article-title, banner, article, contact-me, similar-articles]
      sides: [author]
      width: [8, 4]
  - scope:
      path: ""
      type: "category"
    values:
      layout: "one-column"
      pages: [all-posts-same-category]
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "one-column"
      pages: [article]

collections: 
  category: 
    output: true
    permalink: :collection/:name

###################
# --- Plugins --- #
###################

plugins:
  - jekyll-sitemap
  - jekyll-remote-theme

########################
# --- Custom Theme --- #
########################

remote_theme: Dean-J-K-James/dodo-web-engine-jekyll-theme
