########################
# --- Website Data --- #
########################

baseurl: ""
url: "https://thecodingdodo.com"

#########################################
# --- Default Options for All Pages --- #
#########################################

title: no-title
excerpt: no-description

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "two-column"
      permalink: blog/:slug
      pages: [article-title, banner, article]
      sides: [all-posts-same-category]
      width: [8, 4]
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "one-column"
      pages: [article]

########################
# --- Social Media --- #
########################

social-media:
  twitter: https://twitter.com/thecodingdodo

###################
# --- Plugins --- #
###################

plugins:
  - jekyll-sitemap
  - jekyll-remote-theme

########################
# --- Custom Theme --- #
########################

remote_theme: Dean-J-K-James/dodo-web-engine-jekyll-theme

###########################################
# --- Default Configuration for Theme --- #
###########################################

# Copying the below to each instance of this theme is currently required in
# Jekyll 3. When GitHub updates to Jekyl 4, theme config data is inherited
# by the instance by default, so copying the below data will not be necessary.

# Structure
structure: [cook, menu, page, foot]

# Menus
cook:
  inc: cook
  tag: div
  css: flex flex-row gap-2 text-xs leading-8 p-2 lg:px-[20%] bg-cook text-cook-text !hidden

menu:
  inc: menu
  tag: nav
  css: flex flex-row gap-2 text-xs leading-8 p-2 lg:px-[20%] bg-menu text-menu-text

foot:
  inc: foot
  tag: nav
  css: flex flex-row gap-2 text-xs leading-8 p-8 lg:px-[20%] bg-foot text-foot-text

# Pages
page:
  inc: content
  tag: div
  css: grid grid-cols-12 flex-grow gap-2 lg:gap-4 p-2 lg:p-8 lg:px-[20%] bg-body text-body-text

# Sections
content:
  inc: content
  tag: div
  css: flex flex-col gap-4 p-4 bg-body-accent

all-posts:
  inc: all-posts
  tag: div
  css: grid grid-cols-12 gap-4

all-posts-same-category:
  inc: all-posts-same-category
  tag: div
  css: flex flex-col gap-4

article-title:
  inc: article-title
  tag: header
  css: flex flex-col gap-8 p-4 bg-white rounded

banner:
  inc: banner
  tag: div
  css: 

article:
  inc: content
  tag: article
  css: flex flex-col gap-8 p-4 bg-white